#!/bin/bash
# This script activates "cling" environment of conda installation.

export PATH="/home/astreinw/Environments/miniconda2/bin:$PATH"
source activate cling
echo -e "\"cling\" environment activated."
