#!/bin/bash
# Mount remote filesystem via SSHFS.

echo -e "Connecting to SSHFS: $1"
#sshfs -o idmap=user $1: ~/Remote/gcv
# Split the string to get the hostname
IFS='@ ' read -r -a array <<< "$1"
for el in "${array[@]}"
do
	echo "$el"
done
# Connect to SSHFS, use port if specified.
if [ "$2" != "" ]
then
	sshfs -o idmap=user "$1:" "/home/astreinw/Remote/${array[1]}"
else
	sshfs -p $2 -o idmap=user "$1:" "/home/astreinw/Remote/${array[1]}"
fi

# Old command used
#sshfs -o idmap=user "$1:" "/home/astreinw/Remote/${array[1]}"
