#!/bin/bash
GREEN='\033[0;32m'
NC='\033[0m'

if [ "$1" = "" ]; then
   echo -e "ROS_IP     : ${GREEN}<NOT SET>${NC}"
   echo "" > ~/Scripts/config/ros_ip.conf
   unset ROS_IP 
else
   echo -e "ROS_IP     : ${GREEN}$1${NC}"
   export ROS_IP="$1"
   echo "$ROS_IP" > ~/Scripts/config/ros_ip.conf
fi
